services:
  backend:
    build: ./bug-tracker-backend
    container_name: bug-tracker-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bug_tracker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
  frontend:
    build:
      context: ./bug-tracker-frontend
      dockerfile: Dockerfile.dev
    container_name: bug-tracker-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./bug-tracker-frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    image: postgres:15
    container_name: bug-tracker-db
    restart: always
    environment:
      POSTGRES_DB: bug_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./bug-tracker-backend/scripts/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./bug-tracker-backend/scripts/db/seed.sql:/docker-entrypoint-initdb.d/seed.sql

volumes:
  postgres_data:
