services:
  backend:
    build: ./bug-tracker-backend
    container_name: bug-tracker-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bug_tracker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
  frontend:
    build:
      context: ./bug-tracker-frontend
    container_name: bug-tracker-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - ./bug-tracker-frontend:/app
      - /app/node_modules
    networks:
      - app-network
    environment:
      - CHOKIDAR_USEPOLLING=true

  nginx:
    image: nginx:alpine
    container_name: bug-tracker-nginx
    ports:
      - "80:80"      # Nginx listens on port 80 externally
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Mount your custom Nginx config
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: bug-tracker-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: bug_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./bug-tracker-backend/scripts/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./bug-tracker-backend/scripts/db/seed.sql:/docker-entrypoint-initdb.d/seed.sql

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
